# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'windows-latest'
steps:
  - script: echo hello from Windows with a change in the line
  - script: md sampledir
  - script: dir /od
  - script: $AzCred = Get-Credential -UserName "munisekahr.reddy@gmail.com" && az login -u $AzCred.UserName -p $AzCred.GetNetworkCredential().Password
  - script: az resource list

