# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'windows-latest'
steps:
  - script: echo hello from Windows with a change in the line
  - script: md sampledir
  - script: echo "Verizo@1" >> cred.txt
  - script: dir /od && dir
  
  - pwsh: |
        Write-Output "test output"
        $userId = "munisekhar.reddy@gmail.com"
        $password = get-content -Path "cred.txt" | ConvertTo-SecureString
 
        #Set the powershell credential object
        $cred = New-Object -TypeName System.Management.Automation.PSCredential($userId ,$password)
 
        #log On To Azure Account
        Login-AzureRmAccount -Credential $cred -TenantId "59b2865a-7fb8-4ccb-ab68-72cbca88fc48"
        
  #  $AzCred = Get-Credential -UserName "munisekhar.reddy@gmail.com"
  #- script: Set-Variabl e -Name "AzCred" -Value "Verizon@1"
  #- script: az login -u munisekhar.reddy@gmail.com -p Verizon@1
  #- script: az resource list

